### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by L1ghtn1ng** [thombashi/pingparsing#25] opened 2017-06-10 22:20 UTC
```    ping_parser.parse(result)
  File "/usr/lib/python3.6/site-packages/pingparsing/_pingparsing.py", line 198,            in parse
    self.__parse_linux_ping(ping_message)
  File "/usr/lib/python3.6/site-packages/pingparsing/_pingparsing.py", line 266,            in __parse_linux_ping
    line_list = _to_unicode(ping_message).splitlines()
AttributeError: 'PingResult' object has no attribute 'splitlines'
```
Running 8.0 of pingparsing and getting the above error on archlinux with python 3.6

**Comment by thombashi** [comment] 2017-06-10 23:28
Thank you for your report.

I guess you had passing ``ping`` method result to ``parse`` method like following:

```python
def main():
    ping_parser = pingparsing.PingParsing()
    transmitter = pingparsing.PingTransmitter()
    transmitter.destination_host = "8.8.8.8"
    transmitter.waittime = 10
    result = transmitter.ping()
    ping_parser.parse(result)
```

I could reproduce the problem by this code.
In that case, you could easily fix the code.

```python
def main():
    ping_parser = pingparsing.PingParsing()
    transmitter = pingparsing.PingTransmitter()
    transmitter.destination_host = "8.8.8.8"
    transmitter.waittime = 10
    result = transmitter.ping()
    ping_parser.parse(result.stdout)  # modified line
```

**Comment by L1ghtn1ng** [comment] 2017-06-11 00:41
Think so will need to double check it when I get to work on Monday but it does from me testing your way does work and would be nice to have a changelog saying that there was a breaking change and how to fix it in release notes. Also your python version bage is broken in the readme and the the docs

**Comment by thombashi** [comment] 2017-06-11 01:54
You're absolutely right.

I've change to accept for both ``ping_parser.parse(result)`` and `` ping_parser.parse(result.stdout)`` at ``pingparsing 0.8.2``.
You do not need to change the source code if you upgrade the package.

>your python version bage is broken in the readme and the the docs

Looks like pingparsing PyPI page (python version badge source) always corrupt when I publish the package from Travis CI, I'm not sure how to fix that right now.

**Comment by L1ghtn1ng** [comment] 2017-06-13 11:49
Yes I did have the code as that and have upgraded to 8.2 and my script now works

Sent from phone

________________________________

**Comment by thombashi** [comment] 2017-06-14 12:39
Thank you for sharing.
I'm glad that works for you.

Then, I'll close the issue.

**Closed by thombashi** 2017-06-14 12:39 UTC
